apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grpc-microservices

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - order-deployment.yaml
  - payment-deployment.yaml
  - shipping-deployment.yaml

commonLabels:
  project: grpc-microservices
