apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: grpc-microservices
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"
